- name: install apache2 ubuntu
  tags: web, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

#centos
- name: install apache2 CentOS
  tags: web, apache2, CentOS
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"



#copy file
- name: copy default html file for zite
  tags: apache, apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
