- name: install mariadb ubuntu
  tags: db, mariadb, ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

#centos
- name: install mariadb CentOS
  tags: db, mariadb, CentOS
  dnf:
    name:
      - mariadb
    state: latest
  when: ansible_distribution == "CentOS"


